### ISSUE TITLE
Feature: Add Trigonometric and some basic Statistical Functions 

### ISSUE THREAD

**Issue by Anonymous5164** [MarufHasan24/mathlib-cpp#17]
Since its a math library it would be gread if you just add some common trigonometric functions like sine, cosine and tan and also some commonly used statistical functions like mean, median and mode, and if possible also some probability density and distribution functions (e.g., normal, exponential, binomial)

**Comment by RRMovies** [comment]
@Anonymous5164 Trigonometry is a built-in feature of `cmath`. So it' s not needed to add them. And the other feature will be available soon. If you want you can also contribute
